title: Wasiq Nabi Bakhsh
logo: assests/Profile.png



description: Data & BI Specialist | Tableau Expert | Visualizing Insights 📊✨
show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
