title: Wasiq Nabi Bakhsh
logo: assests/WhatsApp Image 2024-04-09 at 5.44.29 PM.jpeg



description: Data & BI Specialist | Tableau Expert | Visualizing Insights 📊✨
show_downloads: true
theme: jekyll-theme-minimal
